apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: onyx-infra
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: change-me
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: onyx-infra
type: Opaque
stringData:
  REDIS_PASSWORD: change-me
---
apiVersion: v1
kind: Secret
metadata:
  name: onyx-s3-secret
  namespace: onyx-infra
type: Opaque
stringData:
  S3_AWS_ACCESS_KEY_ID: change-me
  S3_AWS_SECRET_ACCESS_KEY: change-me
