# ============================================================================
# API Server Service for Onyx
# ============================================================================
# Service definition for the api-server deployment
# This service is required for NGINX to resolve api-server:8080
# ============================================================================

---
apiVersion: v1
kind: Service
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  type: ClusterIP
  ports:
    - name: api-server-port
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: api-server
