# ============================================================================
# Vespa StatefulSet for Onyx
# ============================================================================
# Vespa vector search engine deployment
# Image: vespaengine/vespa:8.526.15 (from Helm chart)
# Storage: 30Gi persistent volume
# ============================================================================

---
apiVersion: v1
kind: Service
metadata:
  name: vespa-service
  labels:
    app: vespa
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  ports:
    - name: config
      port: 19071
      targetPort: 19071
      protocol: TCP
    - name: query
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: vespa

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vespa
  labels:
    app: vespa
spec:
  serviceName: vespa-service
  replicas: 1
  selector:
    matchLabels:
      app: vespa
  template:
    metadata:
      labels:
        app: vespa
    spec:
      hostname: vespa-0  # Important: Vespa needs stable hostname
      subdomain: vespa-service
      securityContext:
        fsGroup: 1000  # Vespa user group
      containers:
        - name: vespa
          image: vespaengine/vespa:8.526.15
          imagePullPolicy: IfNotPresent
          ports:
            - name: config
              containerPort: 19071
              protocol: TCP
            - name: query
              containerPort: 8081
              protocol: TCP
          env:
            - name: VESPA_SKIP_UPGRADE_CHECK
              value: "true"
          volumeMounts:
            - name: vespa-storage
              mountPath: /opt/vespa/var
          resources:
            requests:
              cpu: 1000m      # Reduced from Helm (4000m) for minimal deployment
              memory: 2Gi     # Reduced from Helm (8Gi) for minimal deployment
            limits:
              cpu: 4000m      # Reduced from Helm (8000m)
              memory: 8Gi     # Reduced from Helm (32Gi)
          livenessProbe:
            httpGet:
              path: /state/v1/health
              port: 19071
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /state/v1/health
              port: 19071
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          securityContext:
            privileged: true  # Required for Vespa
            runAsUser: 0      # Run as root (required by Vespa)
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: vespa-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: "nfs-example"
        volumeMode: "Filesystem"

