# ============================================================================
# Celery Worker - Light for Onyx
# ============================================================================
# Handles lightweight, fast operations
# Image: onyxdotapp/onyx-backend
# Queues: vespa_metadata_sync, connector_deletion, doc_permissions_upsert, etc.
# ============================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-light
  labels:
    app: celery-worker-light
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker-light
  template:
    metadata:
      labels:
        app: celery-worker-light
        scope: onyx-backend-celery
    spec:
      containers:
        - name: celery-worker-light
          image: onyxdotapp/onyx-backend:nightly-20241004
          imagePullPolicy: IfNotPresent
          command:
            - celery
            - -A
            - onyx.background.celery.versioned_apps.light
            - worker
            - --loglevel=INFO
            - --hostname=light@%n
            - -Q
            - vespa_metadata_sync,connector_deletion,doc_permissions_upsert,checkpoint_cleanup,index_attempt_cleanup
          envFrom:
            - configMapRef:
                name: onyx-config
          env:
            # Database credentials from secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_PASSWORD
            # Redis password from secret
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
            # NLTK data path (for air-gapped environments)
            - name: NLTK_DATA
              value: "/usr/local/share/nltk_data"
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - celery -A onyx.background.celery.versioned_apps.light inspect ping -d light@$HOSTNAME
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - celery -A onyx.background.celery.versioned_apps.light inspect ping -d light@$HOSTNAME
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
      restartPolicy: Always

