apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
  username: YOUR_DOCKERHUB_USERNAME  # ⚠️ REPLACE WITH YOUR DOCKERHUB USERNAME
  password: YOUR_DOCKERHUB_PASSWORD  # ⚠️ REPLACE WITH YOUR DOCKERHUB PASSWORD OR ACCESS TOKEN
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
type: kubernetes.io/basic-auth
stringData:
  username: YOUR_GITHUB_USERNAME  # ⚠️ REPLACE WITH YOUR GITHUB USERNAME
  password: YOUR_GITHUB_TOKEN     # ⚠️ REPLACE WITH YOUR GITHUB PERSONAL ACCESS TOKEN
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipeline-sa
secrets:
  - name: dockerhub-secret
  - name: github-secret

