apiVersion: v1
kind: Secret
metadata:
  name: onyx-postgresql
  namespace: onyx-infra
type: Opaque
stringData:
  username: postgres
  password: change-me
---
apiVersion: v1
kind: Secret
metadata:
  name: onyx-redis
  namespace: onyx-infra
type: Opaque
stringData:
  redis_password: change-me
---
apiVersion: v1
kind: Secret
metadata:
  name: onyx-objectstorage
  namespace: onyx-infra
type: Opaque
stringData:
  s3_aws_access_key_id: change-me
  s3_aws_secret_access_key: change-me
  rootUser: minioadmin
  rootPassword: change-me
---
apiVersion: v1
kind: Secret
metadata:
  name: onyx-opensearch
  namespace: onyx-infra
type: Opaque
stringData:
  opensearch_admin_username: admin
  opensearch_admin_password: "ChangeMe123!"
---
apiVersion: v1
kind: Secret
metadata:
  name: onyx-slackbot
  namespace: onyx-infra
type: Opaque
stringData:
  DANSWER_BOT_TOKEN: ""
  DANSWER_BOT_SIGNING_SECRET: ""
  DANSWER_BOT_APP_TOKEN: ""
