apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
  namespace: onyx-infra
data:
  AUTH_TYPE: "basic"
  WEB_DOMAIN: "http://localhost:3000"
  DOMAIN: "localhost"

  POSTGRES_HOST: "postgresql.onyx-infra.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "postgres"

  REDIS_HOST: "redis.onyx-infra.svc.cluster.local"
  REDIS_PORT: "6379"

  VESPA_HOST: "vespa-0.vespa-service.onyx-infra.svc.cluster.local"

  OPENSEARCH_HOST: "opensearch.onyx-infra.svc.cluster.local"
  ENABLE_OPENSEARCH_INDEXING_FOR_ONYX: "true"

  MODEL_SERVER_HOST: "inference-model-server.onyx-infra.svc.cluster.local"
  MODEL_SERVER_PORT: "9000"
  INDEXING_MODEL_SERVER_HOST: "indexing-model-server.onyx-infra.svc.cluster.local"
  INDEXING_MODEL_SERVER_PORT: "9000"

  INTERNAL_URL: "http://api-server.onyx-infra.svc.cluster.local:8080"

  FILE_STORE_BACKEND: "s3"
  S3_ENDPOINT_URL: "https://your-s3-endpoint:443"
  S3_FILE_STORE_BUCKET_NAME: "your-bucket"

  QA_TIMEOUT: "120"
  LOG_LEVEL: "info"
  SKIP_WARM_UP: "true"
  LLM_SOCKET_READ_TIMEOUT: "120"
  MAX_ALLOWED_UPLOAD_SIZE_MB: "100"
