apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
  namespace: onyx-infra
data:
  AUTH_TYPE: "basic"
  WEB_DOMAIN: "http://localhost:3000"
  DOMAIN: "localhost"

  POSTGRES_HOST: "postgresql.onyx-infra.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "postgres"

  REDIS_HOST: "redis.onyx-infra.svc.cluster.local"
  REDIS_PORT: "6379"

  VESPA_HOST: "vespa-0.vespa-service.onyx-infra.svc.cluster.local"

  OPENSEARCH_HOST: "opensearch.onyx-infra.svc.cluster.local"
  ENABLE_OPENSEARCH_INDEXING_FOR_ONYX: "true"
  ENABLE_OPENSEARCH_RETRIEVAL_FOR_ONYX: "false"
  DEFAULT_OPENSEARCH_CLIENT_TIMEOUT_S: "60"
  DEFAULT_OPENSEARCH_QUERY_TIMEOUT_S: "50"

  MODEL_SERVER_HOST: "inference-model-server.onyx-infra.svc.cluster.local"
  MODEL_SERVER_PORT: "9000"
  INDEXING_MODEL_SERVER_HOST: "indexing-model-server.onyx-infra.svc.cluster.local"
  INDEXING_MODEL_SERVER_PORT: "9000"

  INTERNAL_URL: "http://api-server.onyx-infra.svc.cluster.local:8080"

  FILE_STORE_BACKEND: "s3"
  S3_ENDPOINT_URL: "https://your-s3-endpoint:443"
  S3_FILE_STORE_BUCKET_NAME: "your-bucket"
  S3_VERIFY_SSL: "true"
  S3_GENERATE_LOCAL_CHECKSUM: "false"

  QA_TIMEOUT: "120"
  LOG_LEVEL: "info"
  SKIP_WARM_UP: "true"
  LLM_SOCKET_READ_TIMEOUT: "120"
  MAX_ALLOWED_UPLOAD_SIZE_MB: "250"
  DEFAULT_USER_FILE_MAX_UPLOAD_SIZE_MB: "100"
  MAX_FILE_SIZE_BYTES: "2147483648"
  MAX_DOCUMENT_CHARS: "5000000"

  CELERY_WORKER_DOCPROCESSING_CONCURRENCY: "4"
  CELERY_WORKER_DOCFETCHING_CONCURRENCY: "1"
  CELERY_WORKER_USER_FILE_PROCESSING_CONCURRENCY: "2"
  CELERY_WORKER_PRIMARY_CONCURRENCY: "4"
  CELERY_WORKER_LIGHT_CONCURRENCY: "12"
  CELERY_WORKER_HEAVY_CONCURRENCY: "2"
  CELERY_WORKER_LIGHT_PREFETCH_MULTIPLIER: "4"
  NUM_INDEXING_WORKERS: "4"

  DISABLE_INDEX_UPDATE_ON_SWAP: "true"
  ENABLE_MULTIPASS_INDEXING: "false"
  INDEXING_EMBEDDING_MODEL_NUM_THREADS: "4"
