apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: onyx-infra
spec:
  selector:
    app: postgresql
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: onyx-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      securityContext:
        runAsUser: 1001000000
        runAsNonRoot: true
      containers:
        - name: postgresql
          image: postgres:15.2-alpine
          securityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: onyx-postgresql
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: onyx-postgresql
                  key: password
            - name: POSTGRES_DB
              value: postgres
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
