apiVersion: v1
kind: Service
metadata:
  name: web-server
  namespace: onyx-infra
spec:
  selector:
    app: web-server
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: onyx-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
        scope: onyx-frontend
    spec:
      containers:
        - name: web-server
          image: onyxdotapp/onyx-web-server:v3.1.1
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: INTERNAL_URL
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: INTERNAL_URL
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
